# Licensed to the Apache Software Foundation (ASF) under one or more contributor
# license agreements; and to You under the Apache License, Version 2.0.

apiVersion: v1
kind: Namespace
metadata:
  name: hellows
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-cm
  namespace: hellows
data:
  index.html: |
        <!DOCTYPE HTML>
        <html>
            <body>
                Input: <input id="input" type="text" size="10"><br>
                <button id="send" disabled>Send</button><br>
                Output:<b><span id="output"></span></b><br>
            <script>
                var tgt = "wss://hellows.sciabarra.net/hello";
                var socket = new WebSocket(tgt);
                socket.onopen = function(event) {
                    console.log("Connected!")
                    document.getElementById("send").disabled = false
                }
                document.getElementById("send").onclick = function() {
                    data = { "name": document.getElementById("input").value}
                    console.log(data)
                    socket.send(JSON.stringify(data)+"\n")
                }
                socket.onmessage = function(message) {
                    var data = JSON.parse(message.data)
                    console.log(data)
                    document.getElementById("output").innerText = data["golang-main-single"]
                }
            </script>
            </body>
        </html>
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: hellows
  labels:
    app: nginx
spec:
  volumes:
  - name: hello-mnt
    configMap:
      name: hello-cm
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: hello-mnt
      mountPath: "/usr/share/nginx/html"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: hellows
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: hellows
spec:
  rules:
  - host: hellows.sciabarra.net
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-svc
          servicePort: 80
